### PR TITLE
add support for laravel 10

### PR DESCRIPTION
**Pull request by atmonshi**
based on #3 I fixed the falling tests

### CODE REVIEW

**Comment by swapnilsarwe** [comment]
Thanks @atmonshi 🤗

@nerdroid23 - can we get this merged at the earliest now.

**Comment by nerdroid23** [comment]
Thanks, @atmonshi and @swapnilsarwe 💪🏿

**Comment by swapnilsarwe** [comment]
tell me when you tag it @nerdroid23 
so that we can merge this https://github.com/blade-ui-kit/blade-ui-kit.com/pull/106

**Comment by swapnilsarwe** [comment]
@nerdroid23 - can you please tag this MR with a new tag, so that users can take benefit of the latest update.

**Comment by nerdroid23** [comment]
Sorry, I've been very busy @swapnilsarwe. I'll make sure to tag it later today.

**Comment by nerdroid23** [comment]
@swapnilsarwe New [tag](https://github.com/nerdroid23/blade-icomoon/releases/tag/v1.1.0) is up 🚀, Thanks to both you and @atmonshi

**Comment by swapnilsarwe** [comment]
> @swapnilsarwe New [tag](https://github.com/nerdroid23/blade-icomoon/releases/tag/v1.1.0) is up 🚀, Thanks to both you and @atmonshi

Thanks a ton !

**Pull request merged**
