### PR TITLE
Laravel11 support

### PR DESCRIPTION
**Pull request by swapnilsarwe**

### CODE REVIEW

**Review by nerdroid23 — APPROVED** [review]

**Comment by nerdroid23** [comment]
@swapnilsarwe sorry for the late reply, thanks for your work on this!
Could you take a look as of why one of the workflows is failing, please?

**Comment by swapnilsarwe** [comment]
> @swapnilsarwe sorry for the late reply, thanks for your work on this!
> Could you take a look as of why one of the workflows is failing, please?

Yes, it's in my TODO this week. The PHP+Laravel dependency matrix configuration in an action is an issue. Will get that sorted soon.

**Comment by calebdw** [comment]
Can we get Laravel 11 support added? Thanks!

**Comment by nerdroid23** [comment]
@swapnilsarwe Thank you very much and sorry for the delay! 🚀

**Comment by nerdroid23** [comment]
@calebdw it should be ready for Laravel v11 now, give it a try.

**Comment by calebdw** [comment]
Awesome! Thank you!!!

**Pull request merged**
